Adding queen's quay etc. to the tracks graph.
Should have done this a few days ago when Harbourfront was added, because the
locations report code assumes that any vehicle which is on-route is also on
either the tracks or street graph.

By adding the Harbourfront route without the corresponding tracks along queen's
quay etc., generating locations reports raised exceptions like this:

Traceback (most recent call last):
  File "/var/www/main/reports.py", line 169, in make_reports_and_insert_into_db_single_route
    locations_data = traffic.get_recent_vehicle_locations_impl(froute_, direction, datazoom, report_time_)
  File "/var/www/main/traffic.py", line 24, in get_recent_vehicle_locations_impl
    return db.get_recent_vehicle_locations(fudgeroute_, TIME_WINDOW_MINUTES, dir_, datazoom_, time_window_end_=time_, log_=log_)
  File "/var/www/main/db.py", line 606, in get_recent_vehicle_locations
    interp(vis, True, True, direction, datazoom_, time_window, log_=log_)
  File "/var/www/main/db.py", line 778, in interp
    be_clever_, current_conditions_, dir_, datazoom_, log_)
  File "/var/www/main/db.py", line 831, in interp_impl
    lo_vi, hi_vi, time_ratio, lo_idx, hi_idx, grades_, paths_, log_)
  File "/var/www/main/db.py", line 920, in path_interp_single_latlonnheadingnmofr
    i_latlng, i_heading = get_latlngnheading_from_path(path, pieceidx, time_ratio_)
  File "/var/www/main/db.py", line 931, in get_latlngnheading_from_path
    piece = path_.get_piece(pieceidx_)
AttributeError: 'NoneType' object has no attribute 'get_piece'