Fixing rare bug where a message like the one below would appear in the apache error logs, and I think the error icon would appear to the user.  I don't know what the effect would be on the info shown to the user.  They might have had to wait for one more periodic refresh (10 seconds) to get updated info.
I didn't reproduced this bug with the main page, but I did reproduce it with a
test page.  The php and py files for that test are below.

This commit introduces a threading lock on each lru_cache call, including the
call of the user function (if the desired key is not in the cache).  This could
be a performance problem on the server side - maybe now, maybe later - but
hopefully not, because I don't think that there are any examples of
occasionally slow user functions that are called in response to server hits.
They're all supposed to be very fast.   The only potentially slow ones are only
called during graph building, which is done by a developer - not inside of
apache - and probably in a single-threaded environment, where performance is
not critical.

[Wed Nov 04 07:24:19 2015] [error] [client 174.115.121.22] ...
         (pid=32463) Request url: http://ttcskycam.ca/main/callpy.wsgi?module_and_funcname=reports.get_traffic_report&arg0=d4k0l7l0k0j7l5d4&arg1=e8&arg2=f0&arg3=e8&arg4=d4f0e8e9f3e5e9e9e5e8f2d2e8f5f8f0f2f8e8e8d4&_=1446639860967
mod_wsgi (pid=32463): Exception occurred processing WSGI script '/var/www/main/callpy.wsgi'.
Traceback (most recent call last):
  File "/var/www/main/callpy.wsgi", line 114, in application
    output = get_call_func(query_string, referer)
  File "/var/www/main/callpy.wsgi", line 72, in get_call_func
    return call_func(module_and_funcname, args, referer_)
  File "/var/www/main/callpy.wsgi", line 85, in call_func
    r = getattr(__import__(modulename), funcname)(*args_)
  File "./reports.py", line 114, in get_traffic_report
    return get_report('traffic', froute_, dir_, datazoom_, time_, last_gotten_timestr_, log_=log_)
  File "./reports.py", line 53, in get_report
    return get_current_report(report_type_, froute_, direction, datazoom_, last_gotten_timestr_, log_=log_)
  File "./reports.py", line 69, in get_current_report
    return get_current_report_from_db(report_type_, froute_, dir_, datazoom_, last_gotten_timestr_, log_=log_)
  File "./reports.py", line 105, in get_current_report_from_db
    report_json = db.get_report(report_type_, froute_, dir_, datazoom_, latest_report_time)
  File "./lru_cache.py", line 73, in wrapper
    del cache[key], refcount[key]
KeyError: ('locations', 'dundas', 0, 1, 1446630300000L)

test.24972394874134958.php:

<!DOCTYPE html>
<html>
  <head>
		<title>test</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 70%; margin: 0; padding: 0 }
    </style>
    <script type="text/javascript"
		      src="http://maps.googleapis.com/maps/api/js?sensor=false">
					    </script>
		<script type="text/javascript" src="js/richmarker-compiled.js"></script>
		<script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
		<script type="text/javascript" src="js/buckets-minified.js"></script>
		<script type="text/javascript" src="common.js"></script>
		<script type="text/javascript" src="js/infobox_packed.js"></script>
		<script type="text/javascript" src="spatialindex.js"></script>
    <script type="text/javascript">

var g_interval = null;
var g_threadids = new buckets.Set();

function start() {
	console.log('Starting.'); // tdr
	g_threadids.clear();
	g_interval = setInterval(function() {
			//callpy('t.t2', Math.round(Math.random()*2),
			callpy('t.t2', ((new Date()).getTime()/1).toString(),
				{success: function(r_) {
					if(r_ == 'success') {
						//console.log(new Date(), r_);
					} else {
						console.log(new Date(), r_); // tdr
					}
				},
				error: function() {
					console.log('failure'); // tdr
				}}
			);
		}, 1);
}

function stop() {
	clearInterval(g_interval);
	g_interval = null;
	console.log('Stopped.'); // tdr
}

function on_click() {
	if(is_selected('go_checkbox')) {
		start();
	} else {
		stop();
	}
}

function initialize() {

	$('#go_checkbox').click(on_click);
	on_click();

}
    </script>
  </head>
  <body onload="initialize()" >
		<div id="map_canvas" style="width:100%; height:100%"></div>
		<br>
		<label><input id="go_checkbox" type="checkbox" checked />Go</label>
		<p id="p_error"/>
		<p id="p_latlngs"/>
		<p id="p_loading_urls"/>
  </body>
</html>


t.py:

#!/usr/bin/env python

import sys, os, urlparse, json, pprint, time, pickle, xml.dom, xml.dom.minidom, datetime, time, getopt, threading, copy, random
from backport_OrderedDict import *
import traffic, db, vinfo, routes, geom, mc, tracks, util, predictions, system, c, reports, streetlabels, snapgraph, streets, testgraph
from misc import *
import geom
import numpy as np
import thread
from lru_cache import lru_cache

def t():
	return str(thread.get_ident())

g_x = None

@lru_cache(10)
def t2(x_):
	if 1:
		if random.randrange(1000) == 0:
			time.sleep(3)
		return 'success'
	else:
		global g_x
		x = random.randrange(1000000)
		g_x = x
		if g_x == x:
			return 'success'
		else:
			return 'failure'

if __name__ == '__main__':

	pass