Multiprocessing generation of reports (and maybe poll_locations?) was broken. Fixing.  I didn't realize that multiprocessing child processes work a bit like a 'fork' and inherit global variables, such as mc.g_memcache_client.  This seemed to be causing problems.  So now those child processes create their own connection to memcache and the database (via a multiprocessing.Pool 'initializer' argument).   Makes some confusing errors go away.  I think.
Example of confusing error:

Traceback (most recent call last):
  File "/var/www/html/main/reports.py", line 169, in <module>
    make_all_reports_and_insert_into_db_forever()
  File "/var/www/html/main/reports.py", line 157, in make_all_reports_and_insert_into_db_forever
    make_all_reports_and_insert_into_db_once()
  File "/var/www/html/main/reports.py", line 136, in make_all_reports_and_insert_into_db_once
    multiproc(8, make_reports_and_insert_into_db_single_route, [(report_time, froute) for froute in FROUTES])
  File "/var/www/html/main/misc.py", line 884, in multiproc
    returnvals.append(result.get())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
AttributeError: 'list' object has no attribute 'southwest'